package com.yakala.app

object Lang {
    val LANGS = arrayOf("tr", "en", "ru", "zh")
    val NAMES = mapOf("tr" to "Türkçe", "en" to "English", "ru" to "Русский", "zh" to "中文")
    private val S = mapOf(
        "tr" to mapOf(
            "hint" to "Aklına ne geldi?\n(ilk satır başlık olur, zorunlu değil)",
            "search" to "Ara...", "save" to "✓ Kaydet", "voice" to "🎤 Ses", "stt" to "🗣️ Metin", "stop" to "■ Bitir",
            "myNotes" to "📋 NOTLARIM", "frNotes" to "👥 ARKADAŞ NOTLARI",
            "settings" to "⚙️ Ayarlar", "toDark" to "🌙 Karanlık temaya geç", "toLight" to "☀️ Açık temaya geç",
            "backup" to "📤 Yedekle (JSON)", "restore" to "📥 Geri yükle", "about" to "ℹ️ Yakala v2.1",
            "friends" to "👥 Arkadaşlar", "myCode" to "🪪 Kodum", "addFriend" to "➕ Kod ile arkadaş bul",
            "share" to "📨 Davet linki paylaş", "myFriends" to "👥 Arkadaşlarım", "server" to "🔗 Sunucu / isim",
            "codeHint" to "Arkadaşın kodu (6 hane)", "find" to "🔍 Ara", "searching" to "🔍 Aranıyor...",
            "notFound" to "❌ Bu kodda kullanıcı bulunamadı", "addQ" to "bulundu — eklensin mi?", "add" to "✅ Ekle",
            "cancel" to "Vazgeç", "reqTitle" to "👥 Arkadaşlık isteği", "reqMsg" to "seni arkadaş olarak eklemek istiyor",
            "full" to "✅ Tam izin (karşılıklı)", "ask" to "❓ Her seferinde sor", "reject" to "Reddet",
            "sendTo" to "📤 Kime gönderelim?", "whenQ" to "not ne zaman ulaşsın?", "now" to "⚡ Hemen gönder",
            "timed" to "⏰ Zaman seçerek gönder", "remQ" to "için hatırlatıcı eklensin mi?", "remAdd" to "🔔 Hatırlatıcı ekle",
            "remNo" to "➡️ Hatırlatıcısız gönder", "sent" to "gönderildi", "sched" to "⏰ Zamanlandı: ",
            "remWhen" to "⏰ Ne zaman hatırlatayım?", "r1m" to "⚡ 1 dakika sonra (test)", "r1h" to "⏱ 1 saat sonra",
            "rPick" to "📅 Tarih ve saat seç", "rRm" to "🗑 Hatırlatmayı kaldır", "rSet" to "⏰ Hatırlatma kuruldu",
            "rRmd" to "Hatırlatma kaldırıldı", "edit" to "✏️ Düzenle", "play" to "🔊 Çal", "send" to "📤 Arkadaşa gönder",
            "remind" to "⏰ Hatırlat", "pin" to "📌 Sabitle", "unpin" to "📌 Sabitlemeyi kaldır", "del" to "🗑️ Sil",
            "editTitle" to "✏️ Notu düzenle", "rec" to "🔴 Kaydediliyor...", "listen" to "🎙️ Dinliyorum, konuş...",
            "saved" to "✅ Not kaydedildi", "vsaved" to "✅ Sesli not kaydedildi", "playing" to "🔊 Çalıyor",
            "copied" to "🪪 Kod kopyalandı", "fAdded" to "eklendi (karşılıklı)", "reqSent" to "📨 İstek gönderildi",
            "mic" to "Mikrofon izni gerekli", "bSaved" to "✅ Yedek kaydedildi", "restored" to "not geri yüklendi",
            "lang" to "🌐 Dil", "accept" to "✅ Kabul et", "toMine" to "📋 Notlarıma ekle", "vNote" to "Sesli not",
            "noFriends" to "Henüz arkadaş yok", "futureTime" to "Gelecek bir zaman seç", "noPlay" to "Oynatılamadı",
            "recErr" to "Kayıt hatası", "sttNo" to "Cihazda konuşma tanıma yok", "noNet" to "⚠️ İnternet yok, çeviri çalışmaz",
            "noSpeech" to "⚠️ Konuşma algılanmadı", "firstVoice" to "Önce ses kaydını bitir", "firstText" to "Önce metin kaydını bitir",
            "sharedSaved" to "✅ Paylaşılan metin kaydedildi", "newNote" to "📬 Yeni not isteği var", "delTitle" to "Notu sil"
        ),
        "en" to mapOf(
            "hint" to "What's on your mind?\n(first line becomes title, optional)",
            "search" to "Search...", "save" to "✓ Save", "voice" to "🎤 Voice", "stt" to "🗣️ Text", "stop" to "■ Stop",
            "myNotes" to "📋 MY NOTES", "frNotes" to "👥 FRIEND NOTES",
            "settings" to "⚙️ Settings", "toDark" to "🌙 Switch to dark theme", "toLight" to "☀️ Switch to light theme",
            "backup" to "📤 Backup (JSON)", "restore" to "📥 Restore", "about" to "ℹ️ Yakala v2.1",
            "friends" to "👥 Friends", "myCode" to "🪪 My code", "addFriend" to "➕ Find friend by code",
            "share" to "📨 Share invite link", "myFriends" to "👥 My friends", "server" to "🔗 Server / name",
            "codeHint" to "Friend's code (6 digits)", "find" to "🔍 Search", "searching" to "🔍 Searching...",
            "notFound" to "❌ User not found", "addQ" to "found — add?", "add" to "✅ Add",
            "cancel" to "Cancel", "reqTitle" to "👥 Friend request", "reqMsg" to "wants to add you as a friend",
            "full" to "✅ Full permission (mutual)", "ask" to "❓ Ask each time", "reject" to "Reject",
            "sendTo" to "📤 Send to whom?", "whenQ" to "when should it arrive?", "now" to "⚡ Send now",
            "timed" to "⏰ Send at chosen time", "remQ" to "add a reminder for?", "remAdd" to "🔔 Add reminder",
            "remNo" to "➡️ Send without reminder", "sent" to "sent", "sched" to "⏰ Scheduled: ",
            "remWhen" to "⏰ When should I remind?", "r1m" to "⚡ In 1 minute (test)", "r1h" to "⏱ In 1 hour",
            "rPick" to "📅 Pick date & time", "rRm" to "🗑 Remove reminder", "rSet" to "⏰ Reminder set",
            "rRmd" to "Reminder removed", "edit" to "✏️ Edit", "play" to "🔊 Play", "send" to "📤 Send to friend",
            "remind" to "⏰ Remind", "pin" to "📌 Pin", "unpin" to "📌 Unpin", "del" to "🗑️ Delete",
            "editTitle" to "✏️ Edit note", "rec" to "🔴 Recording...", "listen" to "🎙️ Listening, speak...",
            "saved" to "✅ Note saved", "vsaved" to "✅ Voice note saved", "playing" to "🔊 Playing",
            "copied" to "🪪 Code copied", "fAdded" to "added (mutual)", "reqSent" to "📨 Request sent",
            "mic" to "Microphone permission needed", "bSaved" to "✅ Backup saved", "restored" to "notes restored",
            "lang" to "🌐 Language", "accept" to "✅ Accept", "toMine" to "📋 Add to my notes", "vNote" to "Voice note",
            "noFriends" to "No friends yet", "futureTime" to "Pick a future time", "noPlay" to "Cannot play",
            "recErr" to "Recording error", "sttNo" to "No speech recognition on device", "noNet" to "⚠️ No internet, transcription off",
            "noSpeech" to "⚠️ No speech detected", "firstVoice" to "Finish voice recording first", "firstText" to "Finish text recording first",
            "sharedSaved" to "✅ Shared text saved", "newNote" to "📬 New note request", "delTitle" to "Delete note"
        ),
        "ru" to mapOf(
            "hint" to "Что у тебя на уме?\n(первая строка — заголовок, необязательно)",
            "search" to "Поиск...", "save" to "✓ Сохранить", "voice" to "🎤 Аудио", "stt" to "🗣️ Текст", "stop" to "■ Стоп",
            "myNotes" to "📋 МОИ ЗАМЕТКИ", "frNotes" to "👥 ЗАМЕТКИ ДРУЗЕЙ",
            "settings" to "⚙️ Настройки", "toDark" to "🌙 Тёмная тема", "toLight" to "☀️ Светлая тема",
            "backup" to "📤 Резервная копия", "restore" to "📥 Восстановить", "about" to "ℹ️ Yakala v2.1",
            "friends" to "👥 Друзья", "myCode" to "🪪 Мой код", "addFriend" to "➕ Найти по коду",
            "share" to "📨 Поделиться ссылкой", "myFriends" to "👥 Мои друзья", "server" to "🔗 Сервер / имя",
            "codeHint" to "Код друга (6 цифр)", "find" to "🔍 Поиск", "searching" to "🔍 Поиск...",
            "notFound" to "❌ Пользователь не найден", "addQ" to "найден — добавить?", "add" to "✅ Добавить",
            "cancel" to "Отмена", "reqTitle" to "👥 Запрос в друзья", "reqMsg" to "хочет добавить вас в друзья",
            "full" to "✅ Полное разрешение", "ask" to "❓ Спрашивать каждый раз", "reject" to "Отклонить",
            "sendTo" to "📤 Кому отправить?", "whenQ" to "когда доставить?", "now" to "⚡ Сейчас",
            "timed" to "⏰ Ко времени", "remQ" to "добавить напоминание?", "remAdd" to "🔔 Добавить напоминание",
            "remNo" to "➡️ Без напоминания", "sent" to "отправлено", "sched" to "⏰ Запланировано: ",
            "remWhen" to "⏰ Когда напомнить?", "r1m" to "⚡ Через 1 минуту", "r1h" to "⏱ Через час",
            "rPick" to "📅 Дата и время", "rRm" to "🗑 Убрать напоминание", "rSet" to "⏰ Напоминание установлено",
            "rRmd" to "Напоминание убрано", "edit" to "✏️ Изменить", "play" to "🔊 Слушать", "send" to "📤 Отправить другу",
            "remind" to "⏰ Напомнить", "pin" to "📌 Закрепить", "unpin" to "📌 Открепить", "del" to "🗑️ Удалить",
            "editTitle" to "✏️ Изменить заметку", "rec" to "🔴 Запись...", "listen" to "🎙️ Слушаю, говорите...",
            "saved" to "✅ Сохранено", "vsaved" to "✅ Аудио сохранено", "playing" to "🔊 Воспроизведение",
            "copied" to "🪪 Код скопирован", "fAdded" to "добавлен(ы)", "reqSent" to "📨 Запрос отправлен",
            "mic" to "Нужен микрофон", "bSaved" to "✅ Копия сохранена", "restored" to "заметок восстановлено",
            "lang" to "🌐 Язык", "accept" to "✅ Принять", "toMine" to "📋 В мои заметки", "vNote" to "Аудио заметка",
            "noFriends" to "Пока нет друзей", "futureTime" to "Выберите будущее время", "noPlay" to "Не воспроизводится",
            "recErr" to "Ошибка записи", "sttNo" to "Нет распознавания речи", "noNet" to "⚠️ Нет интернета",
            "noSpeech" to "⚠️ Речь не распознана", "firstVoice" to "Сначала завершите запись", "firstText" to "Сначала завершите запись",
            "sharedSaved" to "✅ Текст сохранён", "newNote" to "📬 Новый запрос", "delTitle" to "Удалить заметку"
        ),
        "zh" to mapOf(
            "hint" to "你在想什么？\n(第一行作为标题，可选)",
            "search" to "搜索...", "save" to "✓ 保存", "voice" to "🎤 语音", "stt" to "🗣️ 文本", "stop" to "■ 停止",
            "myNotes" to "📋 我的笔记", "frNotes" to "👥 好友笔记",
            "settings" to "⚙️ 设置", "toDark" to "🌙 深色主题", "toLight" to "☀️ 浅色主题",
            "backup" to "📤 备份", "restore" to "📥 恢复", "about" to "ℹ️ Yakala v2.1",
            "friends" to "👥 好友", "myCode" to "🪪 我的代码", "addFriend" to "➕ 通过代码查找",
            "share" to "📨 分享邀请链接", "myFriends" to "👥 我的好友", "server" to "🔗 服务器/名称",
            "codeHint" to "好友代码（6位）", "find" to "🔍 搜索", "searching" to "🔍 搜索中...",
            "notFound" to "❌ 未找到用户", "addQ" to "已找到 — 添加？", "add" to "✅ 添加",
            "cancel" to "取消", "reqTitle" to "👥 好友请求", "reqMsg" to "想加你为好友",
            "full" to "✅ 完全权限（相互）", "ask" to "❓ 每次询问", "reject" to "拒绝",
            "sendTo" to "📤 发送给谁？", "whenQ" to "何时送达？", "now" to "⚡ 立即发送",
            "timed" to "⏰ 定时发送", "remQ" to "是否添加提醒？", "remAdd" to "🔔 添加提醒",
            "remNo" to "➡️ 不添加提醒", "sent" to "已发送", "sched" to "⏰ 已定时：",
            "remWhen" to "⏰ 何时提醒？", "r1m" to "⚡ 1分钟后（测试）", "r1h" to "⏱ 1小时后",
            "rPick" to "📅 选择日期时间", "rRm" to "🗑 删除提醒", "rSet" to "⏰ 提醒已设置",
            "rRmd" to "提醒已删除", "edit" to "✏️ 编辑", "play" to "🔊 播放", "send" to "📤 发送给好友",
            "remind" to "⏰ 提醒", "pin" to "📌 置顶", "unpin" to "📌 取消置顶", "del" to "🗑️ 删除",
            "editTitle" to "✏️ 编辑笔记", "rec" to "🔴 录音中...", "listen" to "🎙️ 在听，请说...",
            "saved" to "✅ 已保存", "vsaved" to "✅ 语音已保存", "playing" to "🔊 播放中",
            "copied" to "🪪 代码已复制", "fAdded" to "已添加（相互）", "reqSent" to "📨 请求已发送",
            "mic" to "需要麦克风权限", "bSaved" to "✅ 备份已保存", "restored" to "条笔记已恢复",
            "lang" to "🌐 语言", "accept" to "✅ 接受", "toMine" to "📋 加入我的笔记", "vNote" to "语音笔记",
            "noFriends" to "暂无好友", "futureTime" to "请选择未来时间", "noPlay" to "无法播放",
            "recErr" to "录音错误", "sttNo" to "设备无语音识别", "noNet" to "⚠️ 无网络",
            "noSpeech" to "⚠️ 未检测到语音", "firstVoice" to "请先完成录音", "firstText" to "请先完成录音",
            "sharedSaved" to "✅ 已保存分享文本", "newNote" to "📬 新笔记请求", "delTitle" to "删除笔记"
        )
    )
    fun t(l: String, k: String): String = S[l]?.get(k) ?: S["tr"]?.get(k) ?: k
}
