plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace 'com.yakala.app'
    compileSdk 34
    defaultConfig {
        applicationId "com.yakala.app"
        minSdk 24
        targetSdk 34
        versionCode 16
        versionName "1.6"
    }
    signingConfigs {
        yakala {
            storeFile file('../keystore/yakala.jks')
            storePassword 'yakala123'
            keyAlias 'yakala'
            keyPassword 'yakala123'
        }
    }
    buildTypes {
        debug { signingConfig signingConfigs.yakala }
        release { signingConfig signingConfigs.yakala; minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
}
